kind: Deployment
apiVersion: apps/v1
metadata:
   name: tejadevops
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: tejadevops
   template:
      metadata:
        labels:
          app: tejadevops
      spec:
       containers:
        - name: tejadevops
          image: vikashashoke/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
