kind: Service                             
apiVersion: v1
metadata:
  name: tejadevops
  labels:
    app: tejadevops
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: tejadevops                    
  type: LoadBalancer
